### ISSUE TITLE
Doesn't work with spring-data-rest

### ISSUE THREAD

**Issue by fireboy1919** [derjust/spring-data-dynamodb#189] opened 2018-08-08 18:25 UTC
## Problems
1. the tag used here is not supported in 5.0.2: 
  https://github.com/derjust/spring-data-dynamodb/wiki/Spring-Data-REST
Is this no longer needed?

2. When attempting to use the @RepositoryRestResource annotation, I get 
"Couldn't find PersistentEntity for type..." whenever attempting to access the "findAll" parameter.

Using spring-boot-starter-data-rest v2.0.3, spring-data-commons v2.0.8, spring boot v2.0.3

**Comment by fireboy1919** [comment] 2018-08-09 02:10
Looks like this is as simple to fix as just making a new release.  Is it coming soon?

**Comment by derjust** [comment] 2018-08-11 06:11
Duplicate of #15 - 
Release `v5.0.3` pushed to Maven Central :)

**Closed by derjust** 2018-08-11 06:11 UTC
Labels: duplicate
